// indiaStates.js
const states=[
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chhattisgarh",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttar Pradesh",
      "Uttarakhand",
      "West Bengal",
      "Andaman and Nicobar Islands",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Delhi"
    ]; 
const cities = {
    "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Tirupati",
    "Kakinada",
    "Nellore",
    "Guntur",
    "Rajahmundry",
    "Chittoor",
    "Kadapa",
    "Anantapur",
    "Eluru",
    "Srikakulam",
    "Bhimavaram",
    "Proddatur",
    "Machilipatnam",
    "Tanuku",
    "Kurnool",
    "Peddapuram",
    "Kavali",
    "Nandyal",
    "Narsapur",
    "Palakollu",
    "Adoni",
    "Amalapuram",
    "Bapatla",
    "Pithapuram",
    "Tadepalligudem",
    "Jammalamadugu",
    "Rayachoti",
    "Penukonda"
    ],
    "Arunachal Pradesh": [
        "Itanagar",
        "Tawang",
        "Bomdila",
        "Ziro",
        "Aalo",
        "Tezpur",
        "Pasighat",
        "Namsai",
        "Naharlagun",
        "Roing",
        "Tirap",
        "Changlang",
        "Seppa",
        "Lohit",
        "Anjaw",
        "Lower Dibang Valley",
        "Upper Dibang Valley",
        "West Kameng",
        "East Kameng"
    ],
    "Assam": [
      "Guwahati",
    "Dibrugarh",
    "Silchar",
    "Jorhat",
    "Tinsukia",
    "Nagaon",
    "Tezpur",
    "Bongaigaon",
    "Barpeta",
    "Golaghat",
    "Karimganj",
    "Sibsagar",
    "Kokrajhar",
    "Bokakhat",
    "Majuli",
    "Morigaon",
    "Charaideo",
    "Darrang",
    "Dhemaji",
    "Hojai",
    "Lakhimpur",
    "Nalbari",
    "Sonitpur",
    "Kamrup Metropolitan",
    "Kamrup",
    "Hailakandi",
    "Karbi Anglong",
    "Cachar",
    "Biswanath"
    ],
    "Bihar": [
      "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Darbhanga",
    "Munger",
    "Begusarai",
    "Purnia",
    "Nalanda",
    "Vaishali",
    "Saharsa",
    "Chhapra",
    "Buxar",
    "Katihar",
    "Khagaria",
    "Samastipur",
    "Siwan",
    "Arrah",
    "Siwan",
    "Banka",
    "Bihar Sharif",
    "Jamui",
    "Lakhisarai",
    "Saran",
    "West Champaran",
    "East Champaran",
    "Nalanda",
    "Nawada",
    "Sheikhpura",
    "Kishanganj",
    "Madhepura",
    "Purnia",
    "Sitamarhi",
    "Motihari",
    "Aurangabad"
    ],
    "Chhattisgarh": [
        "Raipur",
        "Bilaspur",
        "Durg",
        "Korba",
        "Rajnandgaon",
        "Raigarh",
        "Jagdalpur",
        "Ambikapur",
        "Bhilai",
        "Dhamtari",
        "Janjgir-Champa",
        "Surguja",
        "Mungeli",
        "Koriya",
        "Baloda Bazar",
        "Bemetara",
        "Kabirdham",
        "Jashpur",
        "Balrampur",
        "Sukma",
        "Bijapur",
        "Narayanpur",
        "Kanker",
        "Korba",
        "Mahasamund",
        "Surajpur"
    ],
    "Goa": [
      "Panaji",
    "Vasco da Gama",
    "Margao",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Cortalim",
    "Canacona",
    "Quepem",
    "Sanguem",
    "Dona Paula",
    "Siraulim",
    "Colva",
    "Assagao",
    "Aldona",
    "Verem",
    "Arossim",
    "Cortalim",
    "Chandor",
    "Salcete"
    ],
    "Gujarat": [
      "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Anand",
    "Nadiad",
    "Gandhinagar",
    "Vapi",
    "Mehsana",
    "Navsari",
    "Patan",
    "Valsad",
    "Bhuj",
    "Dahod",
    "Morbi",
    "Porbandar",
    "Veraval",
    "Kheda",
    "Gandhidham",
    "Palanpur",
    "Bharuch",
    "Bulsar",
    "Vadnagar",
    "Unjha",
    "Godhra",
    "Bapunagar",
    "Maninagar",
    "Modasa"
    ],
    "Haryana": [
      "Ambala",
    "Faridabad",
    "Gurugram",
    "Hisar",
    "Karnal",
    "Panipat",
    "Rohtak",
    "Yamunanagar",
    "Sonipat",
    "Jhajjar",
    "Rewari",
    "Palwal",
    "Narnaul",
    "Fatehabad",
    "Bhiwani",
    "Sirsa",
    "Kaithal",
    "Mahendragarh",
    "Charkhi Dadri",
    "Kurukshetra",
    "Jind",
    "Pehowa",
    "Pinjore",
    "Tauru",
    "Ratia",
    "Assandh"
    ],
    "Himachal Pradesh": [
        "Shimla",
        "Manali",
        "Dharamshala",
        "Kullu",
        "Solan",
        "Kangra",
        "Hamirpur",
        "Bilaspur",
        "Mandi",
        "Chamba",
        "Nahan",
        "Una",
        "Palampur",
        "Baijnath",
        "Reckong Peo",
        "Dalhousie",
        "Kasauli",
        "Rohru",
        "Sundernagar",
        "Chintpurni",
        "Nagrota Surian"
    ],
    "Jharkhand": [
      "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro Steel City",
    "Hazaribagh",
    "Deoghar",
    "Giridih",
    "Dumka",
    "Chaibasa",
    "Ramgarh",
    "Sahebganj",
    "Khunti",
    "Pakur",
    "Simdega",
    "Palamu",
    "Latehar",
    "Chatra",
    "Godda",
    "Seraikela",
    "Koderma"
    ],
    "Karnataka": [
      "Bengaluru",
    "Mysuru",
    "Hubli",
    "Dharwad",
    "Mangaluru",
    "Belagavi",
    "Kalaburagi",
    "Bidar",
    "Ballari",
    "Shimoga",
    "Tumkur",
    "Chitradurga",
    "Udupi",
    "Hassan",
    "Chikkamagaluru",
    "Bagalkot",
    "Kolar",
    "Raichur",
    "Kodagu",
    "Davangere",
    "Chikballapur",
    "Mandya",
    "Ramanagaram",
    "Dakshina Kannada",
    "Bijapur",
    "Gadag"
    ],
    "Kerala": [
      "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Kottayam",
    "Thrissur",
    "Malappuram",
    "Palakkad",
    "Kannur",
    "Pathanamthitta",
    "Alappuzha",
    "Idukki",
    "Wayanad",
    "Ernakulam",
    "Kollam",
    "Punalur",
    "Varkala",
    "Ottapalam",
    "Changanassery",
    "Kochi",
    "Adoor",
    "Tirur"
    ],
    "Madhya Pradesh": [
      "Bhopal",
    "Indore",
    "Gwalior",
    "Ujjain",
    "Jabalpur",
    "Sagar",
    "Khandwa",
    "Rewa",
    "Shivpuri",
    "Dewas",
    "Ratlam",
    "Khargone",
    "Satna",
    "Chhindwara",
    "Vidisha",
    "Burhanpur",
    "Mandsaur",
    "Rajgarh",
    "Sehore",
    "Betul",
    "Hoshangabad",
    "Neemuch",
    "Shahdol",
    "Dindori"
    ],
    "Maharashtra": [
        "Mumbai",
        "Pune",
        "Nagpur",
        "Nashik",
        "Thane",
        "Aurangabad",
        "Kolhapur",
        "Solapur",
        "Jalgaon",
        "Amravati",
        "Nanded",
        "Satara",
        "Chandrapur",
        "Parbhani",
        "Ratnagiri",
        "Latur",
        "Sangli",
        "Bhandara",
        "Beed",
        "Washim",
        "Akola",
        "Wardha",
        "Palghar",
        "Gondia",
        "Sindhudurg",
        "Hingoli",
        "Yavatmal",
        "Raigad"
    ],
    "Manipur": [
    "Imphal",
    "Thoubal",
    "Kakching",
    "Churachandpur",
    "Bishnupur",
    "Senapati",
    "Tamenglong",
    "Ukhrul",
    "Chandel",
    "Kangpokpi",
    "Jiribam"
    ],
    "Meghalaya": [
      "Shillong",
    "Tura",
    "Nongstoin",
    "Jowai",
    "Williamnagar",
    "Mawkyrwat",
    "Baghmara",
    "Ribhoi",
    "Nongpoh",
    "Berlapara"
    ],
    "Mizoram": [
        "Aizawl",
        "Lunglei",
        "Champhai",
        "Kolasib",
        "Serchhip",
        "Mamit",
        "Siaha",
        "Lawngtlai",
        "Hnahthial",
        "Khawzawl"
    ],
    "Nagaland": [
      "Kohima",
    "Dimapur",
    "Mokokchung",
    "Wokha",
    "Zunheboto",
    "Mon",
    "Phek",
    "Tuensang",
    "Longleng",
    "Kiphire"
    ],
    "Odisha": [
      "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Berhampur",
    "Balasore",
    "Sambalpur",
    "Puri",
    "Bargarh",
    "Jharsuguda",
    "Koraput",
    "Angul",
    "Dhenkanal",
    "Keonjhar",
    "Rayagada",
    "Bhadrak",
    "Nayagarh",
    "Malkangiri",
    "Kendrapara",
    "Jagatsinghpur"
    ],
    "Punjab": [
      "Amritsar",
    "Ludhiana",
    "Jalandhar",
    "Patiala",
    "Mohali",
    "Bathinda",
    "Hoshiarpur",
    "Moga",
    "Firozpur",
    "Rupnagar",
    "Barnala",
    "Faridkot",
    "Gurdaspur",
    "Sangrur",
    "Kapurthala",
    "Tarn Taran",
    "Sri Muktsar Sahib",
    "Fatehgarh Sahib",
    "Mansa",
    "Sri Anandpur Sahib"
    ],
    "Rajasthan": [
      "Jaipur",
    "Udaipur",
    "Kota",
    "Ajmer",
    "Jodhpur",
    "Bikaner",
    "Alwar",
    "Tonk",
    "Sikar",
    "Pali",
    "Chittorgarh",
    "Rajsamand",
    "Bhilwara",
    "Jhunjhunu",
    "Barmer",
    "Dungarpur",
    "Rishabhdev",
    "Banswara",
    "Nagaur",
    "Sawai Madhopur",
    "Hanumangarh",
    "Jalore",
    "Bundi",
    "Sirohi",
    "Churu",
    "Merta City",
    "Kishangarh",
    "Bundi"
    ],
    "Sikkim": [
      "Gangtok",
    "Mangan",
    "Namchi",
    "Rangpo",
    "Jorethang",
    "Singtam",
    "Gyalshing",
    "Lachung",
    "Pakyong",
    "Lingtam"
    ],
    "Tamil Nadu": [
      "Chennai",
    "Coimbatore",
    "Madurai",
    "Trichy",
    "Salem",
    "Tirunelveli",
    "Erode",
    "Tiruppur",
    "Vellore",
    "Chidambaram",
    "Nagercoil",
    "Tanjore",
    "Dharmapuri",
    "Dindigul",
    "Cuddalore",
    "Karur",
    "Ramanathapuram",
    "Villupuram",
    "Nagapattinam",
    "Thanjavur",
    "Theni",
    "Kanchipuram",
    "Pudukkottai",
    "Karaikudi",
    "Virudhunagar",
    "Kanchipuram",
    "Thiruvarur",
    "Kovai"
    ],
    "Telangana": [
        "Hyderabad",
        "Warangal",
        "Khammam",
        "Karimnagar",
        "Nizamabad",
        "Ramagundam",
        "Mahabubnagar",
        "Adilabad",
        "Nalgonda",
        "Medak",
        "Jagtial",
        "Suryapet",
        "Jagityal",
        "Wanaparthy",
        "Sangareddy",
        "Vikarabad",
        "Peddapalli",
        "Nagarkurnool",
        "Kamareddy",
        "Yadadri Bhuvanagiri",
        "Malkajgiri",
        "Rajanna Sircilla",
        "Khammam",
        "Miryalaguda",
        "Bhadrachalam",
        "Bodhan",
        "Mancherial",
        "Nirmal"
    ],
    "Tripura": [
      "Agartala",
    "Ambassa",
    "Udaipur",
    "Dharmanagar",
    "Kailashahar",
    "Sepahijala",
    "Khowai",
    "Belonia",
    "Sonamura",
    "Ranirbazar",
    "Teliamura",
    "Melaghar",
    "Jirania",
    "Mohanpur",
    "Bagbassa",
    "Bishalgarh",
    "Manu",
    "Chandrapur",
    "Kanchanpur"
    ],
    "Uttar Pradesh": [
      "Agra",
    "Aligarh",
    "Allahabad",
    "Ambedkar Nagar",
    "Amethi",
    "Amroha",
    "Auraiya",
    "Ayodhya",
    "Azamgarh",
    "Badaun",
    "Baghpat",
    "Bahraich",
    "Ballia",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bijnor",
    "Budaun",
    "Bulandshahr",
    "Chandauli",
    "Chitrakoot",
    "Deoria",
    "Etah",
    "Etawah",
    "Faizabad",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hamirpur",
    "Hapur",
    "Hardoi",
    "Hathras",
    "Jhansi",
    "Jalaun",
    "Jaunpur",
    "Kanpur",
    "Kanpur Dehat",
    "Kasganj",
    "Kaushambi",
    "Kushinagar",
    "Lakhimpur Kheri",
    "Lalitpur",
    "Lucknow",
    "Mau",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffarnagar",
    "Pilibhit",
    "Pratapgarh",
    "Raebareli",
    "Rampur",
    "Saharanpur",
    "Sant Kabir Nagar",
    "Shahjahanpur",
    "Shravasti",
    "Siddharthnagar",
    "Sitapur",
    "Sonbhadra",
    "Sultanpur",
    "Unnao",
    "Varanasi"

    ],
    "Uttarakhand": [
        "Almora",
        "Bageshwar",
        "Chamoli",
        "Champawat",
        "Dehradun",
        "Haridwar",
        "Nainital",
        "Pauri Garhwal",
        "Pithoragarh",
        "Rudraprayag",
        "Tehri Garhwal",
        "Udham Singh Nagar",
        "Uttarkashi"
    ],
    "West Bengal": [
      "Alipurduar",
    "Asansol",
    "Baharampur",
    "Bardhaman",
    "Barrackpore",
    "Basirhat",
    "Bhatpara",
    "Cooch Behar",
    "Durgapur",
    "Haldia",
    "Howrah",
    "Jalpaiguri",
    "Kolkata",
    "Malda",
    "Medinipur",
    "Murarai",
    "Nadia",
    "Raniganj",
    "Siliguri",
    "Srirampore",
    "Tamluk"
    ],
    "Andaman and Nicobar Islands": [
      "Port Blair",
    "Campbell Bay",
    "Diglipur",
    "Havelock Island",
    "Mayabunder",
    "Ritchie's Archipelago",
    "Wandoor",
    "Long Island",
    "Baratang Island"
    ],
    
    "Dadra and Nagar Haveli and Daman and Diu": [
      "Daman",
      "Diu",
      "Silvassa"
    ],
    "Lakshadweep": [
      "Kavaratti"
    ],
    "Delhi": [
      "Delhi"
    ],
    "Puducherry": [
      "Puducherry"
    ]
  };
  
  export { states, cities };
  
  